PawsNClaws/Controllers/OwnerAssetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PawsNClaws.DATA.EF;
using Microsoft.AspNet.Identity;
using System.IO;

namespace PawsNClaws.Controllers
{
    public class OwnerAssetsController : Controller
    {
        private PawsNClawsEntities db = new PawsNClawsEntities();

        // GET: OwnerAssets
        [Authorize]
        public ActionResult Index()
        {
            if(User.IsInRole("Admin"))
            {
                var accounts = db.OwnerAssets.ToList();
                return View(accounts);
            }
            var user = User.Identity.GetUserId();
            var accountByOwner = db.OwnerAssets.Where(abo => abo.OwnerID == user && abo.IsActive == true);
            return View(accountByOwner.ToList());
            
        }

        // GET: OwnerAssets/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            return View(ownerAsset);
        }

        // GET: OwnerAssets/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: OwnerAssets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerAssetID,AssetName,OwnerID,AssetPhoto,SpecialNotes,IsActive,DateAdded")]
        OwnerAsset ownerAsset, HttpPostedFileBase AssetPhoto)
        {
            if (ModelState.IsValid)
            {
                ownerAsset.OwnerID = User.Identity.GetUserId();

                //***********  USER INFO AND FILE IMAGE UPLOAD
                #region User Information and File/Image Upload
                //default image will be noImage.jpg if no image is provided
                string image = "noImage.jpg";

                //check that image upload contains valid image
                if (AssetPhoto != null)
                {

                    //yes
                    //reassign the fileName to the variable that represents the default img
                    image = AssetPhoto.FileName;

                    //create a variable and retrieve the extension from the image
                    string ext = image.Substring(image.LastIndexOf("."));

                    //create a list of valid file extensions - (whitelist)
                    string[] goodExts = new string[] { ".jpg", ".png", ".jpeg", ".gif" };

                    //check our extension against that list
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        //as long as our extension is in that list
                        //rename the file to a unique file name and add the extension
                        image = Guid.NewGuid() + ext;
                        //save the new file to the website

                        AssetPhoto.SaveAs(Server.MapPath("~/Content/assets/images/UserImages/" + image));

                    }
                    //if an invalid extension is provided
                    else
                    {
                        //go back to the default page
                        image = "noImage.jpg";
                    }
                }

                //No Matter What add the image name to the database object
                ownerAsset.AssetPhoto = image;
                #endregion

                ownerAsset.DateAdded = DateTime.Now;
                ownerAsset.IsActive = true;
                db.OwnerAssets.Add(ownerAsset);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(ownerAsset);
        }

        // GET: OwnerAssets/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            return View(ownerAsset);
        }

        // POST: OwnerAssets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OwnerAssetID,AssetName,OwnerID,AssetPhoto,SpecialNotes,IsActive,DateAdded")]
        OwnerAsset ownerAsset, HttpPostedFileBase AssetPhoto)
        {
            if (ModelState.IsValid)
            {
                ownerAsset.OwnerID = User.Identity.GetUserId();

                //******************** FILE IMAGE UPLOAD
                #region User Information and File/Image Upload

                //if image is valid
                if (AssetPhoto != null)
                {

                    //store the new file name
                    string image = AssetPhoto.FileName;

                    //extract the extension and save it in a variable
                    string ext = image.Substring(image.LastIndexOf("."));

                    //valid file extensions - (whitelist)
                    string[] goodExts = new string[] { ".jpg", ".png", ".jpeg", ".gif" };

                    //check our extension against that list
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        //if it's good...guid it.
                        //rename the file to a unique file name and add the extension
                        image = Guid.NewGuid() + ext;
                        //save the new file to the website

                        AssetPhoto.SaveAs(Server.MapPath("~/Content/assets/images/UserImages/" + image));

                        //remove the original(previous) image from website (NOT default image)
                        if (ownerAsset.AssetPhoto != "noImage.jpg")
                        {
                            System.IO.File.Delete(Server.MapPath("~/Content/assets/images/UserImages/" +
                                ownerAsset.AssetPhoto));
                        }
                        //save to database
                        ownerAsset.AssetPhoto = image;

                    }
                }

                //if upload is null the HiddenFor() will save original file
                #endregion

                db.Entry(ownerAsset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ownerAsset);
        }

        // GET: OwnerAssets/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            if (ownerAsset == null)
            {
                return HttpNotFound();
            }
            return View(ownerAsset);
        }

        // POST: OwnerAssets/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OwnerAsset ownerAsset = db.OwnerAssets.Find(id);
            db.OwnerAssets.Remove(ownerAsset);

            //remove associated image(keeping default)
            if (ownerAsset.AssetPhoto != "noImage.jpg" && ownerAsset.AssetPhoto != null)
            {
                System.IO.File.SetAttributes(Server.MapPath("~/Content/assets/images/UserImages/" +
                    ownerAsset.AssetPhoto), FileAttributes.Normal);
                System.IO.File.Delete(Server.MapPath("~/Content/assets/images/UserImages/" +
                    ownerAsset.AssetPhoto));
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PawsNClaws/Views/OwnerAssets/Create.cshtml
@model PawsNClaws.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "Add a Pet";
}

@using (Html.BeginForm("Create", "OwnerAssets", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="oaContainer">
        <div id="oaCreateContents">
            <h2 class="listHeader">@ViewBag.Title</h2>

            <div id="oaCreatePhoto">
                <label>Upload Pet Image</label>:
                <p>
                    <input type="file" style="margin-bottom:.5em;" name="AssetPhoto" class="oaCreatePhoto" />
                </p>
            </div>
            <div class="clearfix"></div>
            <br />
            <p>
                @Html.LabelFor(model => model.AssetName, htmlAttributes: new { @class = "control-label push-left" })
                @Html.EditorFor(model => model.AssetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssetName, "", new { @class = "text-danger" })
            </p>
            <p>
                @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label push-left" })
                @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control", @style = "resize:none" } })
                @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
            </p>
        </div>
        <div class="clearfix"></div>
        <div class="viewFooters">
            <div class="col-md-7 oaFooterLeftCreate">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="col-md-3 oaFooterRightCreate">
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PawsNClaws/Views/OwnerAssets/Delete.cshtml
@model PawsNClaws.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "Deleting " + Model.AssetName;
}

<div class="deleteOutterDiv">
    <h2>@ViewBag.Title</h2>

    <h3>Are you sure you want to delete the profile for your pet: <span class="myWarning">@Model.AssetName</span>?</h3>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="display:inline-block;">
            <input type="submit" value="Yes" class="btn btn-primary" /> |
            @Html.ActionLink("No", "Index", null, new { @class = "btn btn-danger" })
        </div>
    }
</div>

PawsNClaws/Views/OwnerAssets/Details.cshtml
@model PawsNClaws.DATA.EF.OwnerAsset

@{
    ViewBag.Title = Model.AssetName + "'s" + " Details";
}

<div class="oaContainer">
    <div id="oaDetailBody">
            <h2 class="listHeader">@ViewBag.Title</h2>
        <div id="oaLeft">
            <p>
                <img class="imagesInView" src="~/Content/assets/images/UserImages/@Model.AssetPhoto"
                     alt="@Model.AssetName" height="250" width="250" />
            </p>
        </div>
        <div class="clearfix"></div>
        <div id="oaRight">
            <p>
                <label>@Html.DisplayNameFor(model => model.SpecialNotes):</label>
            </p>
            <p>
                <span id="oaRightNotes">
                    @Html.DisplayFor(model => model.SpecialNotes)
                </span>
            </p>
            <div id="oaActiveandDate">
                <p>
                    @Html.DisplayNameFor(model => model.IsActive)
                    @Html.DisplayFor(model => model.IsActive)
                </p>
                <p>
                    @Html.DisplayNameFor(model => model.DateAdded):
                    @Html.DisplayFor(model => model.DateAdded)
                </p>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="viewFooters">
            <div class="col-md-7">
                @Html.ActionLink("Return", "Index", null, new { @class = "btn btn-danger" })
            </div>
            <div class="col-md-3">
                @Html.ActionLink("Update", "Edit", new { id = Model.OwnerAssetID }, new { @class = "btn btn-primary" })
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

PawsNClaws/Views/OwnerAssets/Edit.cshtml
@model PawsNClaws.DATA.EF.OwnerAsset

@{
    ViewBag.Title = "Update " + Model.AssetName;
}

@using (Html.BeginForm("Edit", "OwnerAssets", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.OwnerAssetID)
    @Html.HiddenFor(model => model.AssetPhoto)
    @Html.HiddenFor(model => model.DateAdded)

    <div class="oaContainer" id="oaEditContainer">
        <h2 class="listHeader">@ViewBag.Title</h2>
        <div id="oaEditContent">
            <div id="oaEditLeft">
                <p></p>
                <label>Current Image: </label>
                <br />
                <img class="imagesInView" src="~/Content/assets/images/UserImages/@Model.AssetPhoto" alt="@Model.AssetName" height="250" width="250" />
                <br />
                <label id="oaEditNewImage">Change Image</label>:
                <input type="file" style="margin-bottom:.1em;" name="AssetPhoto" />
            </div>
            <div class="clearfix"></div>
            <div id="oaEditRight">
                <p>
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2", @id = "oaIsActiveText" })
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </p>
                <p>
                    @Html.LabelFor(model => model.AssetName, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.AssetName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AssetName, "", new { @class = "text-danger" })
                </p>
                <p style="line-height:inherit">
                    @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control", @style = "resize:none" } })
                    @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                </p>
            </div>
            <div class="clearfix"></div>
            <div class="viewFooters">
                <div class="col-md-7 oaFooterLeft">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                </div>
                <div class="col-md-3 oaFooterRight">
                    <input type="submit" value="Update Pet" class="btn btn-primary" />
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PawsNClaws/Views/OwnerAssets/Index.cshtml
@model IEnumerable<PawsNClaws.DATA.EF.OwnerAsset>

@{
    ViewBag.Title = "Your Registered Pets";
}

<div id="oaIndexContainer">
    <div id="oaIndexContent">
        <h2 class="listHeader">@ViewBag.title</h2>

        <p id="oaIndexCreate">
            @Html.ActionLink("Add New Pet", "Create")
        </p>
        <table class="table" id="clientPetList">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.AssetPhoto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.AssetName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SpecialNotes)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td class="oaPetImage">
                            <img class="imagesInView" src="~/Content/assets/images/UserImages/@item.AssetPhoto" alt="@item.AssetName" height="75" width="75" />
                        </td>
                        <td>
                            @Html.ActionLink(item.AssetName, "Details", new { id = item.OwnerAssetID })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SpecialNotes)
                        </td>
                        @if (Request.IsAuthenticated)
                {
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.OwnerAssetID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.OwnerAssetID })
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "lengthChange": false
            });
        });
    </script>
}