PawsNClaws/Controllers/UserAdminController.cs
using PawsNClaws.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System;
using PawsNClaws.DATA.EF;

namespace PawsNClaws.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        //Create the context to get to EF
        PawsNClawsEntities ctx = new PawsNClawsEntities();

        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, 
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel,
            params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                        }
                    }
                    #region Create user object

                    //No Matter What add the image name to the database object
                    //Create user object as well
                    UserDetail info = new UserDetail()
                    {
                        UserID = user.Id,
                        FirstName = userViewModel.FirstName,
                        LastName = userViewModel.LastName,
                    };
                    //add the UserDetails Object to EF
                    ctx.UserDetails.Add(info);
                    //Sent the object to the database as a record
                    ctx.SaveChanges();
                    var users = await UserManager.Users.ToListAsync();
                    return RedirectToAction("Index",users);
                    #endregion
                }

                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();
                }
                //return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }

                #region Delete the UserDetails associated with User
                var member = ctx.UserDetails.Where(ud => ud.UserID == id).Single();

                //remove userDetail object
                ctx.UserDetails.Remove(member);

                //save changes
                ctx.SaveChanges();
                #endregion
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

PawsNClaws/Views/UsersAdmin/Create.cshtml
@model PawsNClaws.Models.RegisterViewModel
@{
    ViewBag.Title = "Create New User Account";
}


    @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-error" })
        <div class="usersContainer">
            <h2 class="listHeader">@ViewBag.Title</h2>

            <div class="form-group">
                @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">
                    Select User Role
                </label>
                <div class="col-md-10">
                    @foreach (var item in (SelectList)ViewBag.RoleId)
                {
                        <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline pull-left"/>
                        @Html.Label(item.Value, new { @class = "control-label pull-left", @style="Display:inline-block" })
                    }
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-7">
                    <input type="submit" class="btn btn-primary" value="Create" />
                </div>
                <div class="col-md-3">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
                </div>

            </div>
        </div>
    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PawsNClaws/Views/UsersAdmin/Delete.cshtml
@model PawsNClaws.Models.ApplicationUser

@{
    ViewBag.Title = "Delete User";
}

<div class="deleteOutterDiv">

    <h2>@ViewBag.Title</h2>

    <h3>Are you sure you want to delete this User: <span class="myWarning">@Model.UserName</span>?</h3>
      
        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-primary" /> |
                @Html.ActionLink("No", "Index", null, new { @class = "btn btn-danger" })
            </div>
        }
    </div>

PawsNClaws/Views/UsersAdmin/Details.cshtml
@model PawsNClaws.Models.ApplicationUser

@{
    ViewBag.Title = "User Roles Detail";
}


<div class="usersContainer">
    <div id="usersAdminDetailContent">
        <h2 class="listHeader">@ViewBag.Title</h2>

        <div>
            <dl class="dl-horizontal" id="uaDetailBody">
                <dt id="uaTitle">
                    User Email:
                </dt>
                <dd id="uaEmailAddress">
                    @Html.DisplayFor(model => model.UserName)
                </dd>
            </dl>
        </div>
        <h4 id="uaRolesH4">List of roles for this user:</h4>
        @if (ViewBag.RoleNames.Count == 0)
        {
            <hr />
            <p>No roles found for this user.</p>
        }

        <table class="table" id="uaDetailsTable">

            @foreach (var item in ViewBag.RoleNames)
            {
                <tr>
                    <td id="uaRoleTD">
                        @item
                    </td>
                </tr>
            }
        </table>
        <div class="clearfix"></div>
        <div class="viewFooters">
            <div class="col-md-7">
                @Html.ActionLink("Update", "Edit", null, new { id = Model.Id, @class = "btn btn-primary" })
            </div>
            <div class="col-md-3">
                @Html.ActionLink("Return", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>

PawsNClaws/Views/UsersAdmin/Edit.cshtml
@model PawsNClaws.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit User Role / Email";
}

<div id="userAdminEditContainer">

    <h2 class="listHeader">@ViewBag.Title</h2>

    @using (Html.BeginForm("Edit", "UsersAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.FirstName)
            @Html.HiddenFor(model => model.LastName)

            <div class="form-group row">
                <p id="userAdminEditRolesLabel">
                    @Html.Label("Roles", new { @class = "control-label push-left col-md-2", @id="uaRoles" })
                </p>

                    <span class="col-md-10" id="userAdminEditCheckbox">
                        @foreach (var item in Model.RolesList)
                {
                            <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                            @Html.Label(item.Value, new { @class = "control-label" })
                        }
                    </span>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @id="uaEmail"})
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group row" id="uaFooter">
                <div class="col-md-offset-2 col-md-7">
                    <input type="submit" value="Update User" class="btn btn-primary" id="uaSubmit"/>
                </div>
                <div class="col-md-3 text-right">
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger", @id="uaDanger" })
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PawsNClaws/Views/UsersAdmin/Index.cshtml
@model IEnumerable<PawsNClaws.Models.ApplicationUser>

@{
    ViewBag.Title = "List of All Registered Users";
}
@{
    //to access the UserDetails for display
    var ctx = new PawsNClaws.DATA.EF.PawsNClawsEntities();
    var userDetail = ctx.UserDetails.ToList();
}
<div class="viewsContainer">
    <h2 class="listHeader">@ViewBag.Title</h2>
    <p class="indexViewsCreateLink">
        @Html.ActionLink("Create New Account", "Create")
    </p>
    <table class="table" id="userAdminTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Name")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @if (userDetail.Any())
                        {
                            @Html.DisplayFor(x => userDetail.Where(ud => ud.UserID == item.Id).SingleOrDefault().FullName)
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                {
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id })

                            @if (User.IsInRole("Admin"))
                            {
                                @:| @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        }
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "lengthChange": false
            });
        });
    </script>
}